services:
  town-of-saviom-frontend:
    build: .
    restart: always
    # This container stays internal; Nginx will talk to it
    ports:
      - "80:80"

networks:
  town-of-saviom-shared-net:
    external: true